bash /hpc2hdd/home/zyang398/yangzhch6/projs/reasoning_baselines/rllm/scripts/verify/Qwen2.5-Math-7B-openr1-nothink-3k-step100-verify.sh
bash /hpc2hdd/home/zyang398/yangzhch6/projs/reasoning_baselines/rllm/scripts/verify/Qwen2.5-Math-7B-openr1-nothink-3k-step200-verify.sh
bash /hpc2hdd/home/zyang398/yangzhch6/projs/reasoning_baselines/rllm/scripts/verify/Qwen2.5-Math-7B-openr1-nothink-3k-step300-verify.sh
bash /hpc2hdd/home/zyang398/yangzhch6/projs/reasoning_baselines/rllm/scripts/verify/Qwen2.5-Math-7B-openr1-nothink-3k-step400-verify.sh
bash /hpc2hdd/home/zyang398/yangzhch6/projs/reasoning_baselines/rllm/scripts/verify/Qwen2.5-Math-7B-openr1-nothink-3k-step500-verify.sh
bash /hpc2hdd/home/zyang398/yangzhch6/projs/reasoning_baselines/rllm/scripts/verify/Qwen2.5-Math-7B-openr1-nothink-3k-step500-verify.sh
bash /hpc2hdd/home/zyang398/yangzhch6/projs/reasoning_baselines/rllm/scripts/verify/Qwen2.5-Math-7B-openr1-nothink-3k-step500-verify.sh
bash /hpc2hdd/home/zyang398/yangzhch6/projs/reasoning_baselines/rllm/scripts/verify/Qwen2.5-Math-7B-openr1-nothink-3k-step500-verify.sh
bash /hpc2hdd/home/zyang398/yangzhch6/projs/reasoning_baselines/rllm/scripts/verify/Qwen2.5-Math-7B-openr1-nothink-3k-step500-verify.sh
bash /hpc2hdd/home/zyang398/yangzhch6/projs/reasoning_baselines/rllm/scripts/verify/Qwen2.5-Math-7B-openr1-nothink-3k-step500-verify.sh
bash /hpc2hdd/home/zyang398/yangzhch6/projs/reasoning_baselines/rllm/scripts/verify/Qwen2.5-Math-7B-openr1-nothink-3k-step500-verify.sh
bash /hpc2hdd/home/zyang398/yangzhch6/projs/reasoning_baselines/rllm/scripts/verify/Qwen2.5-Math-7B-openr1-nothink-3k-step500-verify.sh